local particles = { }

particles['dodge'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/dodge.png"))
particles['dodge']:setParticleLifetime(0.35, 0.75)
particles['dodge']:setSpread(2 * math.pi)
particles['dodge']:setSpeed(3, 10)
particles['dodge']:setSizeVariation(1)
particles['dodge']:setSizes(1.25, 1.2, 1.15, 1.05, 0.95, 0.75, 0.4, 0)
particles['dodge']:setColors(255,255,255,255, 255,255,255,200, 255,255,255,100, 255,255,255,0)
particles['dodge']:setAreaSpread('normal', 2, 4)

particles['redblood'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/redbloodpart.png"))
particles['redblood']:setParticleLifetime(0.65, 0.9)
particles['redblood']:setEmissionRate(10)
particles['redblood']:setSpread(2 * math.pi)
particles['redblood']:setSpeed(15, 25)
particles['redblood']:setSizeVariation(1)
particles['redblood']:setSizes(1.15, 1, 0.8, 0.3, 0)
particles['redblood']:setColors(255, 255, 255, 255, 150, 100, 100, 200, 50, 10, 10, 0)
particles['redblood']:setRelativeRotation(true)
particles['redblood']:setAreaSpread('normal', 4, 4)

particles['dirt'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/dirt.png"))
particles['dirt']:setParticleLifetime(0.65, 0.78)
particles['dirt']:setEmissionRate(10)
particles['dirt']:setSpread(2 * math.pi)
particles['dirt']:setSpeed(15, 25)
particles['dirt']:setSizeVariation(1)
particles['dirt']:setSizes(1.15, 1, 0.9, 0.7, 0)
particles['dirt']:setColors(255, 255, 255, 255, 150, 100, 100, 225, 50, 10, 10, 0)
particles['dirt']:setRelativeRotation(true)
particles['dirt']:setAreaSpread('normal', 4, 4)

particles['flight'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/flight.png"), 10000)
particles['flight']:setParticleLifetime(0.5, 0.6)
particles['flight']:setSizes(1, 0.5, 0.3, 0)
particles['flight']:setSpin(2 * math.pi, 2 * math.pi)
particles['flight']:setSpeed(0.75, 0.85)
particles['flight']:setSpread(2 * math.pi, 2 * math.pi)
particles['flight']:setRelativeRotation(true)

particles['lightflight'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/lightflight.png"), 10000)
particles['lightflight']:setParticleLifetime(0.5, 0.6)
particles['lightflight']:setSizes(1, 0.5, 0.3, 0)
particles['lightflight']:setSpin(math.pi / 2, math.pi)
particles['lightflight']:setSpeed(0.45, 0.65)
particles['lightflight']:setSpread(math.pi, 2 * math.pi)
particles['lightflight']:setRelativeRotation(true)

particles['magicflight'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/magicflight.png"), 10000)
particles['magicflight']:setParticleLifetime(0.5, 0.6)
particles['magicflight']:setSizes(1, 0.5, 0.3, 0)
particles['magicflight']:setSpin(math.pi / 2, math.pi)
particles['magicflight']:setSpeed(0.45, 0.65)
particles['magicflight']:setSpread(math.pi, 2 * math.pi)
particles['magicflight']:setRelativeRotation(true)

particles['fireflight'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/fireflight.png"), 10000)
particles['fireflight']:setParticleLifetime(0.5, 0.6)
particles['fireflight']:setSizes(1, 0.5, 0.3, 0)
particles['fireflight']:setSpin(math.pi / 2, math.pi)
particles['fireflight']:setSpeed(0.45, 0.65)
particles['fireflight']:setSpread(math.pi, 2 * math.pi)
particles['fireflight']:setRelativeRotation(true)

particles['magicflight2'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/magicflight2.png"), 10000)
particles['magicflight2']:setParticleLifetime(0.5, 0.6)
particles['magicflight2']:setSizes(1, 0.5, 0.3, 0)
particles['magicflight2']:setSpin(math.pi / 2, math.pi)
particles['magicflight2']:setSpeed(0.45, 0.65)
particles['magicflight2']:setSpread(math.pi, 2 * math.pi)
particles['magicflight2']:setRelativeRotation(true)

particles['magiccast'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/magiccast.png"), 10000)
particles['magiccast']:setParticleLifetime(0.5, 0.6)
particles['magiccast']:setSizes(1, 0.5, 0.3, 0)
particles['magiccast']:setSpin(math.pi / 2, math.pi)
particles['magiccast']:setSpeed(0.45, 0.65)
particles['magiccast']:setSpread(math.pi, 2 * math.pi)
particles['magiccast']:setRelativeRotation(true)

particles['lightcast'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/lightcast.png"), 10000)
particles['lightcast']:setParticleLifetime(0.5, 0.6)
particles['lightcast']:setSizes(1, 0.5, 0.3, 0)
particles['lightcast']:setSpin(math.pi / 2, math.pi)
particles['lightcast']:setSpeed(0.45, 0.65)
particles['lightcast']:setSpread(math.pi, 2 * math.pi)
particles['lightcast']:setRelativeRotation(true)

particles['fireexo'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/fireexo.png"), 10000)
particles['fireexo']:setParticleLifetime(0.35, 0.55)
particles['fireexo']:setSizes(0, 1, 0.7, 0.5, 0)
particles['fireexo']:setColors(255,255,255,255, 200,200,200,200, 0,0,0,150)
particles['fireexo']:setSpin(math.pi / 2, math.pi)
particles['fireexo']:setSpeed(0.45, 0.65)
particles['fireexo']:setSpread(math.pi, 2 * math.pi)
particles['fireexo']:setAreaSpread('normal', 10, 10)
particles['fireexo']:setRelativeRotation(true)

particles['waterstep'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/waterstep.png"), 1000)
particles['waterstep']:setAreaSpread('normal', 2, 2)
particles['waterstep']:setParticleLifetime(0.55, 0.65)
particles['waterstep']:setSizes(0, 0.2, 0.4, 0.6, 0.8, 1, 1.05, 1.1)
particles['waterstep']:setColors(255, 255, 255, 255, 255, 255, 255, 200, 255, 255, 255, 100, 255, 255, 255, 0)
particles['waterstep']:setSpin(math.pi * 2)

particles['fireexo2'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/fireexo2.png"), 10000)
particles['fireexo2']:setParticleLifetime(0.35, 0.55)
particles['fireexo2']:setSizes(0, 1, 0.7, 0.5, 0)
particles['fireexo2']:setColors(255,255,255,255, 200,200,200,200, 0,0,0,150)
particles['fireexo2']:setSpin(math.pi / 2, math.pi)
particles['fireexo2']:setSpeed(0.45, 0.65)
particles['fireexo2']:setSpread(math.pi, 2 * math.pi)
particles['fireexo2']:setAreaSpread('normal', 7.5, 7.5)
particles['fireexo2']:setRelativeRotation(true)

particles['firecast'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/firecast.png"), 10000)
particles['firecast']:setParticleLifetime(0.5, 0.6)
particles['firecast']:setSizes(1, 0.5, 0.3, 0)
particles['firecast']:setSpin(math.pi / 2, math.pi)
particles['firecast']:setSpeed(0.45, 0.65)
particles['firecast']:setSpread(math.pi, 2 * math.pi)
particles['firecast']:setRelativeRotation(true)

particles['firepart'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/firepart.png"), 10000)
particles['firepart']:setParticleLifetime(0.5, 0.6)
particles['firepart']:setSizes(1, 0.5, 0.3, 0)
particles['firepart']:setSpin(math.pi / 2, math.pi)
particles['firepart']:setSpeed(0.45, 0.65)
particles['firepart']:setSpread(math.pi, 2 * math.pi)
particles['firepart']:setRelativeRotation(true)
particles['firepart']:setAreaSpread('normal', 1, 1)

particles['magiccast2'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/magiccast2.png"), 10000)
particles['magiccast2']:setParticleLifetime(0.5, 0.6)
particles['magiccast2']:setSizes(1, 0.5, 0.3, 0)
particles['magiccast2']:setSpin(math.pi / 2, math.pi)
particles['magiccast2']:setSpeed(0.45, 0.65)
particles['magiccast2']:setSpread(math.pi, 2 * math.pi)
particles['magiccast2']:setRelativeRotation(true)

particles['healthrestored'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/healthrestored.png"))
particles['healthrestored']:setParticleLifetime(0.5, 1.5)
particles['healthrestored']:setSpread(math.pi / 6)
particles['healthrestored']:setDirection(3 * math.pi / 2)
particles['healthrestored']:setSizes(0.75, 0.5, 0.15, 0)
particles['healthrestored']:setSpeed(10, 40)
particles['healthrestored']:setLinearDamping(1, 10)
particles['healthrestored']:setSpin(1, math.pi)
particles['healthrestored']:setAreaSpread('normal', 4, 8)

particles['darkmatterintake'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/darkmatterintake.png"))
particles['darkmatterintake']:setParticleLifetime(0.5, 1.5)
particles['darkmatterintake']:setSpread(math.pi / 6)
particles['darkmatterintake']:setDirection(3 * math.pi / 2)
particles['darkmatterintake']:setSizes(0.75, 0.5, 0.15, 0)
particles['darkmatterintake']:setSpeed(10, 40)
particles['darkmatterintake']:setLinearDamping(1, 10)
particles['darkmatterintake']:setSpin(1, math.pi)
particles['darkmatterintake']:setAreaSpread('normal', 3, 6)

particles['smoke'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/smoke.png"), 10000)
particles['smoke']:setParticleLifetime(0.85, 1.05)
particles['smoke']:setSpread(math.pi / 6)
particles['smoke']:setDirection(3 * math.pi / 2)
particles['smoke']:setColors(255, 255, 255, 100, 255, 255, 255, 255, 0, 0, 0, 255)
particles['smoke']:setSizes(0.55, 0.3, 0.1, 0)
particles['smoke']:setSpin(1, math.pi)
particles['smoke']:setSpeed(1, 10)
particles['smoke']:setLinearAcceleration(1, 2, 3)
particles['smoke']:setRelativeRotation(true)
particles['smoke']:setRadialAcceleration(2, 5)
particles['smoke']:setAreaSpread('normal', 2, 2)

particles['fog'] = love.graphics.newParticleSystem(love.graphics.newImage("dat/img/part/fog.png"), 10000)
particles['fog']:setParticleLifetime(3, 3)
particles['fog']:setSpread(math.pi / 6)
particles['fog']:setDirection(3 * math.pi / 2)
particles['fog']:setColors(255, 255, 255, 100, 255, 255, 255, 255, 0, 0, 0, 255)
particles['fog']:setSizes(0.55, 0.3, 0.1, 0)
particles['fog']:setSpin(2, 2.5)
particles['fog']:setSpeed(1, 2)
particles['fog']:setLinearAcceleration(1, 1)
particles['fog']:setRelativeRotation(true)
particles['fog']:setRadialAcceleration(2, 3)
particles['fog']:setAreaSpread('normal', 2, 2)

particles['cryoheal'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/cryoheal.png"), 10000)
particles['cryoheal']:setParticleLifetime(1.3)
particles['cryoheal']:setEmissionRate(0)
particles['cryoheal']:setAreaSpread('uniform', 0, love.graphics.getHeight() / 1.5)
particles['cryoheal']:setSpeed(200)
particles['cryoheal']:setSpread(math.pi * 2)
particles['cryoheal']:setSizeVariation(1)
particles['cryoheal']:setColors(0, 0, 0, 0, 255, 255, 255, 255, 255, 255, 255, 0)
particles['cryoheal']:setLinearAcceleration(0, 0)
particles['cryoheal']:setDirection(3 * math.pi / 2)
particles['cryoheal']:setColors(255,255,255,255, 230,230,230,230, 150,150,150,150, 0,0,0,0)

particles['matterdropped'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/matterdropped.png"))
particles['matterdropped']:setParticleLifetime(0.5, 3)
particles['matterdropped']:setSpread(math.pi / 6)
particles['matterdropped']:setDirection(3 * math.pi / 2)
particles['matterdropped']:setSizes(0.75, 0.5, 0.15, 0)
particles['matterdropped']:setSpeed(10, 25)
particles['matterdropped']:setLinearDamping(1, 10)
particles['matterdropped']:setSpin(1, math.pi)
particles['matterdropped']:setAreaSpread('normal', 2, 4)

particles['matterpickup'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/matterdropped.png"))
particles['matterpickup']:setParticleLifetime(0.35, 0.75)
particles['matterpickup']:setSpread(math.pi / 6)
particles['matterpickup']:setDirection(3 * math.pi / 2)
particles['matterpickup']:setSizes(0.75, 0.5, 0.15, 0)
particles['matterpickup']:setSpeed(10, 25)
particles['matterpickup']:setLinearDamping(1, 10)
particles['matterpickup']:setSpin(1, math.pi)
particles['matterpickup']:setAreaSpread('normal', 2, 4)

particles['matterdropped2'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/matterdropped2.png"), 1000)
particles['matterdropped2']:setAreaSpread('normal', 0, 0)
particles['matterdropped2']:setParticleLifetime(1)
particles['matterdropped2']:setSizes(0, 0.2, 0.6, 0.8, 1, 1.1, 1.15, 1.18)
particles['matterdropped2']:setColors(255, 255, 255, 255, 255, 255, 255, 200, 255, 255, 255, 100, 255, 255, 255, 0)

particles['matterdropped3'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/matterdropped3.png"), 1000)
particles['matterdropped3']:setAreaSpread('normal', 0, 0)
particles['matterdropped3']:setParticleLifetime(1)
particles['matterdropped3']:setSizes(0, 0.2, 0.6, 0.8, 1, 1.1, 1.15, 1.18)
particles['matterdropped3']:setColors(255, 255, 255, 255, 255, 255, 255, 200, 255, 255, 255, 100, 255, 255, 255, 0)

particles['matterdropped4'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/matterdropped.png"))
particles['matterdropped4']:setParticleLifetime(0.5, 3)
particles['matterdropped4']:setSpread(math.pi / 6)
particles['matterdropped4']:setDirection(3 * math.pi / 2)
particles['matterdropped4']:setSizes(0.75, 0.5, 0.15, 0)
particles['matterdropped4']:setSpeed(10, 25)
particles['matterdropped4']:setLinearDamping(1, 10)
particles['matterdropped4']:setSpin(1, math.pi)
particles['matterdropped4']:setAreaSpread('normal', 2, 4)

particles['sweat'] = love.graphics.newParticleSystem(love.graphics.newImage("/dat/img/part/sweat.png"))
particles['sweat']:setAreaSpread('normal', 2, 0)
particles['sweat']:setParticleLifetime(0.25, 0.55)
particles['sweat']:setSizes(1, 1, 1, 0.9, 0.7, 0)
particles['sweat']:setColors(255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 255, 0)
particles['sweat']:setSpeed(15, 35)
particles['sweat']:setDirection(2 * math.pi - math.pi / 2)
particles['sweat']:setLinearDamping(1, 10)
particles['sweat']:setSpin(0.1, 0.25)
particles['sweat']:setTangentialAcceleration(5, 15)
particles['sweat']:setRelativeRotation(true)

return particles