local weapons = { }

weapons.stiletto = {
	name = 'stiletto',
	dname = 'Stiletto',
	img = 'stiletto',
	icon = love.graphics.newImage("/dat/img/playerType/stilettoicon.png"),
	dx = {north = -5, south = 5, east = -4, west = 4},
	dy = {north = 1, south = 2, east = 1, west = 1},
	rot = {north = 0 + math.pi * 0.1, south = 0 -math.pi * 0.1, east = 0 - math.pi * 0.1, west = 0 + math.pi * 0.1},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 15,
	offhand = true,
	dtype = 'thrust',
	baseDamage = 35,
	aiAttackRange = 40,
	staminaCost = 8,
	backstabBonus = 5,
	type = 'attack',
	offattack = {'offhandstab'},
	scaling = {
		strength = 0,
		dexterity = 1.5,
		intelligence = 0,
		soulpower = 0,
	},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 4},
		south = {x = -6, y = 3, rot = math.pi / 4},
		east = {x = 3, y = 3, rot = math.pi / 4},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 4},
	},
	weight = 2,
	stundam = 0.35,
	bdam = 6,
	desc = 'A lightweight thrusting sword.  Rapiers have high attack speeds, but lower damage.',
	knockback = -0.05,
}

weapons.kiteshield = {
	name = 'kiteshield',
	dname = 'Kite Shield',
	img = 'kiteshield',
	icon = love.graphics.newImage("/dat/img/playerType/kiteshieldicon.png"),
	dx = {north = -5, south = 5, east = -5, west = 3},
	dy = {north = 2, south = 2, east = 2, west = 2},
	rot = {north = 0, south = 0, east = math.pi * 1.9, west = math.pi * 0.1},
	stun = {x = -4, y = 2, rot = math.pi * 0.1},
	dodge = {
		north = {1, -3, math.pi / 4, math.pi / 10, 0},
		south = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
		east = {1, -1, math.pi / 4, math.pi / 10, 0},
		west = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
	},
	ox = 15,
	oy = 15,
	offhand = true,
	type = 'block',
	offattack = {'shield'},
	block = {
		slash = 90,
		thrust = 90,
		crush = 90,
		magic = 55,
		fire = 55,
		solar = 55,
	},
	staminaCost = 0,
	staminaGuard = 20,
	stability = 20,
	weight = 7,
	desc = 'Standard issue shield used by knights.  Provides great defenses and adequate stability.'
}

weapons.standardshield = {
	name = 'standardshield',
	dname = 'Standard Shield',
	img = 'standardshield',
	icon = love.graphics.newImage("/dat/img/playerType/standardshieldicon.png"),
	dx = {north = -5, south = 5, east = -5, west = 3},
	dy = {north = 2, south = 2, east = 2, west = 2},
	rot = {north = 0, south = 0, east = math.pi * 1.9, west = math.pi * 0.1},
	stun = {x = -4, y = 2, rot = math.pi * 0.1},
	dodge = {
		north = {1, -3, math.pi / 4, math.pi / 10, 0},
		south = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
		east = {1, -1, math.pi / 4, math.pi / 10, 0},
		west = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
	},
	ox = 15,
	oy = 15,
	offhand = true,
	type = 'block',
	offattack = {'shield'},
	block = {
		slash = 80,
		thrust = 80,
		crush = 80,
		magic = 45,
		fire = 45,
		solar = 45,
	},
	staminaCost = 0,
	staminaGuard = 30,
	stability = 15,
	weight = 5,
	desc = 'Standard issue shield used by the men at arms.  Provides adequate defenses and decent stability.'
}

weapons.towershield = {
	name = 'towershield',
	dname = 'Tower Shield',
	img = 'towershield',
	icon = love.graphics.newImage("/dat/img/playerType/towershieldicon.png"),
	dx = {north = -5, south = 5, east = -5, west = 5},
	dy = {north = 2, south = 2, east = 2, west = 2},
	rot = {north = 0, south = 0, east = math.pi * 1.9, west = math.pi * 0.1},
	stun = {x = -4, y = 2, rot = math.pi * 0.1},
	dodge = {
		north = {1, -3, math.pi / 4, math.pi / 10, 0},
		south = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
		east = {1, -1, math.pi / 4, math.pi / 10, 0},
		west = {-1, -1, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 10, 0},
	},
	ox = 15,
	oy = 15,
	offhand = true,
	type = 'block',
	offattack = {'shield'},
	block = {
		slash = 100,
		thrust = 100,
		crush = 100,
		magic = 70,
		fire = 70,
		solar = 70,
	},
	staminaCost = 0,
	staminaGuard = 20,
	weight = 12,
	stability = 35,
	desc = 'A heavy shield that is difficult to control, and even more difficult to break down.',
}

weapons.offhand = {
	name = 'offhand', 
	dname = 'Emtpy',
	img = 'hand',
	dx = {north = -3, south = 4, east = 0, west = 1},
	dy = {north = 3, south = 3, east = 3, west = 3},
	rot = {north = 0, south = 0, east = 0, west = 0},
	stun = {x = 0, y = 0, rot = 0},
	ox = 2, 
	oy = 2,
	lightattack = {'stab2'},
	dtype = 'crush',
	baseDamage = 30,
	aiAttackRange = 40,
	staminaCost = 10,
	backstabBonus = 2,
	scaling = {
		strength = 0.4,
		dexterity = 0.01,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 0,
	stundam = 1.1,
	bdam = 40,
}

weapons.bosshand = {
	name = 'bosshand', 
	dname = 'Emtpy',
	img = 'bosshand',
	dx = {north = 4, south = -3, east = 5, west = -5},
	dy = {north = 3, south = 3, east = 3, west = 3},
	rot = {north = 0, south = 0, east = 0, west = 0},
	stun = {x = 0, y = 0, rot = 0},
	ox = 2, 
	oy = 3,
	lightattack = {'stab2'},
	twohand = true,
	dtype = 'crush',
	baseDamage = 30,
	aiAttackRange = 40,
	staminaCost = 10,
	backstabBonus = 2,
	scaling = {
		strength = 0.4,
		dexterity = 0.01,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 0,
	stundam = 1.1,
	bdam = 40,
}

weapons.hand = {
	name = 'hand', 
	dname = 'Emtpy',
	img = 'hand',
	dx = {north = 4, south = -3, east = 6, west = -5},
	dy = {north = 3, south = 3, east = 3, west = 3},
	rot = {north = 0, south = 0, east = 0, west = 0},
	stun = {x = 0, y = 0, rot = 0},
	ox = 2, 
	oy = 2,
	lightattack = {'stab2'},
	dtype = 'crush',
	baseDamage = 30,
	aiAttackRange = 40,
	staminaCost = 10,
	backstabBonus = 2,
	scaling = {
		strength = 1,
		dexterity = 1,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 0,
	stundam = 0.3,
	bdam = 2,
	knockback = -0.15,
}

weapons.spear = {
	name = 'spear',
	dname = 'Spear',
	img = 'spear',
	icon = love.graphics.newImage("/dat/img/playerType/spearicon.png"),
	dx = {north = 6, south = -6, east = 6, west = -6},
	dy = {north = 5, south = 5, east = 5, west = 5},
	rot = {north = math.pi * 1.5, south = math.pi * 1.5, east = math.pi * 1.5, west = math.pi * 1.5},
	stun = {x = -8, y = 2, rot = 0},
	ox = 6,
	oy = 25,
	lightattack = {'stab1'},
	dtype = 'thrust',
	baseDamage = 65,
	aiAttackRange = 60,
	staminaCost = 20,
	backstabBonus = 3.25,
	dodge = {
		north = {-1, 0, 2 * math.pi - math.pi / 4 - math.pi / 4 - math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 4 - math.pi / 10, -1 * math.pi / 2},
		south = {1, 0, 2 * math.pi - math.pi / 4 - math.pi / 4 + math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 4 + math.pi / 10, -1 * math.pi / 2},
		east = {-1, 0, 2 * math.pi - math.pi / 4 - math.pi / 4 - math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 4 - math.pi / 10, -1 * math.pi / 2},
		west = {1, 0, 2 * math.pi - math.pi / 4 - math.pi / 4 + math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 4 + math.pi / 10, -1 * math.pi / 2},
	},
	sprint = {
		north = {x = 5, y = 4, rot = 2 * math.pi - math.pi / 10 - math.pi / 2},
		south = {x = -5, y = 4, rot = 2 * math.pi + math.pi / 10 - math.pi / 2},
		east = {x = 6, y = 4, rot = math.pi / 10 - math.pi / 2},
		west = {x = -6, y = 4, rot = 2 * math.pi - math.pi / 10 - math.pi / 2},
	},
	scaling = {
		strength = 0.5,
		dexterity = 1,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 7,
	stundam = 0.7,
	bdam = 10,
	desc = 'Standard spear used by many soldiers.  The long range makes it suited to keeping enemies away.',
	knockback = -0.2,
}

weapons.longbow = {
	name = 'longbow',
	dname = 'Longbow',
	img = 'longbow',
	icon = love.graphics.newImage("/dat/img/playerType/longbowicon.png"),
	dx = {north = 0, south = 0, east = 2, west = 0},
	dy = {north = 4, south = -2, east = 2, west = 2},
	rot = {north = math.pi * 1.5, south = math.pi * 0.5, east = math.pi * 0.25, west = math.pi * 0.75},
	stun = {x = 3, y = 2, rot = 0},
	ox = 15,
	oy = 15,
	lightattack = {'pull'},
	dtype = 'thrust',
	baseDamage = 55,
	aiAttackRange = 250,
	staminaCost = 30,
	twohand = true,
	backstabBonus = 2,
	scaling = {
		strength = 0.5,
		dexterity = 1,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 3,
	stundam = 0.2,
	bdam = 8,
	desc = 'A bow commonly used by hunters and soldiers.  It\'s design is known for always being dependable.',
	knockback = -0.1
}

weapons.bosshalberd = {
	name = 'bosshalberd',
	dname = 'Guardian Halberd',
	img = 'bosshalberd',
	icon = love.graphics.newImage("/dat/img/playerType/greatswordicon.png"),
	dx = {north = -4, south = 4, east = 2, west = -1},
	dy = {north = -8, south = -3, east = -3, west = -3},
	rot = {north = math.pi / 2 + math.pi / 1.6 - math.pi / 4, south = 2 * math.pi - math.pi * 0.15, east = 2 * math.pi - math.pi / 2.6, west = math.pi / 2.6},
	stun = {x = 2, y = 2, rot = 0},
	ox = 62,
	oy = 66,
	lightattack = {'swordsmash1'},
	dtype = 'slash',
	baseDamage = 75,
	aiAttackRange = 80,
	staminaCost = 40,
	flipWepDrawOrder = true,
	backstabBonus = 2,
	twohand = true,
	dodge = {
		north = {-3, -3, math.pi - math.pi / 4, math.pi - math.pi / 4 - math.pi / 24,  math.pi - math.pi / 4 - math.pi / 12},
		south = {3, 3, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 24, 2 * math.pi - math.pi / 4 - math.pi / 12},
		east = {3, -3, 2 * math.pi - math.pi / 1.5, (2 * math.pi) - (math.pi / 1.5) - math.pi / 24, (2 * math.pi) - (math.pi / 1.5) - math.pi / 12},
		west = {-3, -3, math.pi * 0.5 * 1.25, math.pi * 0.5 * 1.25 + math.pi / 24, math.pi * 0.5 * 1.25 + math.pi / 12},
	},
	sprint = {
		north = {x = -3, y = -7, rot = math.pi - math.pi / 12},
		south = {x = 3, y = -4, rot = 2 * math.pi - math.pi / 12},
		east = {x = 0, y = -3, rot = 2 * math.pi - math.pi / 2},
		west = {x = 0, y = -3, rot = math.pi * 0.5},
	},
	scaling = {
		strength = 0.4,
		dexterity = 0.01,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 20,
	stundam = 1.1,
	bdam = 40,
	desc = 'Halberd used by the spirit dedicated to guarding the Chamber of Awakening.',
	knockback = -0.25
}

weapons.greatsword = {
	name = 'greatsword',
	dname = 'Greatsword',
	img = 'greatsword',
	icon = love.graphics.newImage("/dat/img/playerType/greatswordicon.png"),
	dx = {north = -4, south = 4, east = 2, west = -1},
	dy = {north = -8, south = -3, east = -3, west = -3},
	rot = {north = math.pi / 2 + math.pi / 1.6 - math.pi / 4, south = 2 * math.pi - math.pi * 0.15, east = 2 * math.pi - math.pi / 2.6, west = math.pi / 2.6},
	stun = {x = 2, y = 2, rot = 0},
	ox = 64,
	oy = 64,
	lightattack = {'swordsmash1'},
	dtype = 'crush',
	baseDamage = 155,
	aiAttackRange = 80,
	staminaCost = 40,
	twohand = true,
	flipWepDrawOrder = true,
	shieldBreaker = true,
	backstabBonus = 2,
	dodge = {
		north = {-3, -3, math.pi - math.pi / 4, math.pi - math.pi / 4 - math.pi / 24,  math.pi - math.pi / 4 - math.pi / 12},
		south = {3, 3, 2 * math.pi - math.pi / 4, 2 * math.pi - math.pi / 4 - math.pi / 24, 2 * math.pi - math.pi / 4 - math.pi / 12},
		east = {3, -3, 2 * math.pi - math.pi / 1.5, (2 * math.pi) - (math.pi / 1.5) - math.pi / 24, (2 * math.pi) - (math.pi / 1.5) - math.pi / 12},
		west = {-3, -3, math.pi * 0.5 * 1.25, math.pi * 0.5 * 1.25 + math.pi / 24, math.pi * 0.5 * 1.25 + math.pi / 12},
	},
	sprint = {
		north = {x = -3, y = -7, rot = math.pi - math.pi / 12},
		south = {x = 3, y = -4, rot = 2 * math.pi - math.pi / 12},
		east = {x = 0, y = -3, rot = 2 * math.pi - math.pi / 2},
		west = {x = 0, y = -3, rot = math.pi * 0.5},
	},
	scaling = {
		strength = 1.75,
		dexterity = 0,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 15,
	stundam = 1.1,
	bdam = 40,
	desc = 'A large chunk of iron that was chisled into a sword.  It\'s weight makes it difficult to wield and slow to swing.',
	knockback = -0.25
}

weapons.pyroflame = {
	name = 'pyroflame',
	dname = 'Pyromancer\'s Flame',
	img = 'pyromancy',
	icon = love.graphics.newImage("/dat/img/playerType/pyroflameicon.png"),
	dx = {north = -4, south = 5, east = -5, west = 4},
	dy = {north = 2, south = 2, east = 2, west = 2},
	rot = {north = math.pi * 0.1, south = 0 - math.pi * 0.1, east = math.pi * 0.1, west = 0 - math.pi * 0.1},
	stun = {x = 2, y = 2, rot = 0},
	ox = 16,
	oy = 16,
	castOy = 0,
	offhand = true,
	offattack = {'pyro'},
	dtype = 'fire',
	baseDamage = 5,
	aiAttackRange = 40,
	staminaCost = 0,
	backstabBonus = 4,
	handPart = 'firepart',
	scaling = {
		strength = 0,
		dexterity = 0,
		intelligence = 0.75,
		soulpower = 0.75,
	},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 4},
		south = {x = -6, y = 3, rot = math.pi / 4},
		east = {x = 5, y = 3, rot = math.pi / 4},
		west = {x = -6, y = 3, rot = 2 * math.pi - math.pi / 4},
	},
	type = 'attack',
	weight = 2,
	stundam = 0.3,
	bdam = 7,
	desc = 'A small glove that allows one to channel their inner flames.',
	knockback = -0.15,
}

weapons.staff = {
	name = 'staff',
	dname = 'Sorcery Staff',
	img = 'staff1',
	icon = love.graphics.newImage("/dat/img/playerType/staff1icon.png"),
	dx = {north = 4, south = -6, east = 5, west = -6},
	dy = {north = 2, south = 4, east = 2, west = 2},
	rot = {north = math.pi * 0.1, south = 0 - math.pi * 0.1, east = math.pi * 0.1, west = 0 - math.pi * 0.1},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 18,
	castOy = -13,
	lightattack = {'cast'},
	dtype = 'magic',
	baseDamage = 5,
	aiAttackRange = 40,
	staminaCost = 0,
	backstabBonus = 4,
	scaling = {
		strength = 0,
		dexterity = 0,
		intelligence = 1.5,
		soulpower = 0,
	},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 4},
		south = {x = -6, y = 3, rot = math.pi / 4},
		east = {x = 5, y = 3, rot = math.pi / 4},
		west = {x = -6, y = 3, rot = 2 * math.pi - math.pi / 4},
	},
	weight = 2,
	stundam = 0.3,
	bdam = 7,
	desc = 'A lightweight staff used to conduct soreceries.',
	knockback = -0.15,
}

weapons.rapier = {
	name = 'rapier',
	dname = 'Rapier',
	img = 'rapier',
	icon = love.graphics.newImage("/dat/img/playerType/rapiericon.png"),
	dx = {north = 5, south = -7, east = 5, west = -6},
	dy = {north = 2, south = 4, east = 2, west = 2},
	rot = {north = 0 - math.pi * 0.1, south = math.pi * 0.1, east = math.pi * 0.1, west = 0 - math.pi * 0.1},
	stun = {x = 2, y = 2, rot = 0},
	ox = 16,
	oy = 26,
	lightattack = {'stab2'},
	dtype = 'thrust',
	baseDamage = 60,
	aiAttackRange = 48,
	staminaCost = 14,
	backstabBonus = 4,
	scaling = {
		strength = 0,
		dexterity = 2,
		intelligence = 0,
		soulpower = 0,
	},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 4},
		south = {x = -6, y = 3, rot = math.pi / 4},
		east = {x = 3, y = 3, rot = math.pi / 4},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 4},
	},
	weight = 4,
	stundam = 0.3,
	bdam = 10,
	desc = 'A lightweight thrusting sword.  Rapiers have high attack speeds, but lower damage.',
	knockback = -0.15,
}

weapons.battleaxe = {
	name = 'battleaxe',
	dname = 'Battle Axe',
	img = 'battleaxe',
	icon = love.graphics.newImage("/dat/img/playerType/smallclubicon.png"),
	dx = {north = 4, south = -4, east = 4, west = -5},
	dy = {north = 0, south = -2, east = -2, west = -2},
	rot = {north = 0 - math.pi / 3, south = 0 + math.pi / 3, east = 0 - math.pi / 2.7, west = 0 + math.pi / 2.7},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 3.5},
		south = {x = -6, y = 3, rot = math.pi / 3.5},
		east = {x = 3, y = 3, rot = math.pi / 2.5},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 2.5},
	},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 24,
	lightattack = {'swing4'},
	dtype = 'slash',
	flipWepDrawOrder = true,
	baseDamage = 95,
	aiAttackRange = 50,
	staminaCost = 30,
	twohand = true,
	backstabBonus = 2,
	scaling = {
		strength = 1.5,
		dexterity = 0.35,
		intelligence = 0,
		soulpower = 0,
	},
	sprint = {
		north = {x = 3, y = -5, rot = 0 - math.pi / 1.5},
		south = {x = -4, y = -3, rot = 0 + math.pi / 1.8},
		east = {x = 2, y = -3, rot = 2 * math.pi - math.pi / 2},
		west = {x = -4, y = -3, rot = math.pi * 0.5},
	},
	weight = 8,
	stundam = 0.55,
	bdam = 13,
	desc = 'A heavy axe favored by bandits and mercenaries.  It\'s heavy weight makes it suitable for warriors of great strength.',
	knockback = -0.15,
}

weapons.smallclub = {
	name = 'smallclub',
	dname = 'Small Club',
	img = 'club1',
	icon = love.graphics.newImage("/dat/img/playerType/smallclubicon.png"),
	dx = {north = 7, south = -7, east = 6, west = -7},
	dy = {north = 2, south = 4, east = 2, west = 2},
	rot = {north = 0 + math.pi / 12, south = 0 - math.pi / 12, east = 0 + math.pi / 6, west = 0 - math.pi / 6},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 3.5},
		south = {x = -6, y = 3, rot = math.pi / 3.5},
		east = {x = 3, y = 3, rot = math.pi / 2.5},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 2.5},
	},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 26,
	lightattack = {'swing3'},
	dtype = 'crush',
	baseDamage = 60,
	aiAttackRange = 40,
	staminaCost = 22,
	backstabBonus = 3,
	scaling = {
		strength = 1.25,
		dexterity = 0.25,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 5,
	stundam = 0.4,
	bdam = 13,
	desc = 'A small club commonly found in the frontier systems.  Its light weight and ease to create make it popular where resources are scarce.',
	knockback = -0.15,
}

weapons.gargsword = {
	name = 'gargsword',
	dname = 'Gargoyle Shortsword',
	img = 'gargsword',
	icon = love.graphics.newImage("/dat/img/playerType/shortswordicon.png"),
	dx = {north = 7, south = -7, east = 5, west = -5},
	dy = {north = 2, south = 4, east = 2, west = 2},
	rot = {north = 5 * math.pi / 3, south = math.pi / 3, east = math.pi / 3, west = 5 * math.pi / 3},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 3.5},
		south = {x = -6, y = 3, rot = math.pi / 3.5},
		east = {x = 3, y = 3, rot = math.pi / 2.5},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 2.5},
	},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 26,
	castOy = -19,
	lightattack = {'swing1', 'swing2'},
	dtype = 'slash',
	baseDamage = 75,
	aiAttackRange = 40,
	staminaCost = 18,
	backstabBonus = 3,
	scaling = {
		strength = 0.1,
		dexterity = 0.4,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 5,
	stundam = 0.2,
	bdam = 10,
	desc = 'A reliable sword whose design is as old as man.  Shortswords are fast, powerful, and easy to use.',
	knockback = -0.15,
}

weapons.shortsword = {
	name = 'shortsword',
	dname = 'Shortsword',
	img = 'shortsword',
	icon = love.graphics.newImage("/dat/img/playerType/shortswordicon.png"),
	dx = {north = 7, south = -7, east = 5, west = -5},
	dy = {north = 2, south = 4, east = 2, west = 2},
	rot = {north = 5 * math.pi / 3, south = math.pi / 3, east = math.pi / 3, west = 5 * math.pi / 3},
	sprint = {
		north = {x = 6, y = 3, rot = 2 * math.pi - math.pi / 3.5},
		south = {x = -6, y = 3, rot = math.pi / 3.5},
		east = {x = 3, y = 3, rot = math.pi / 2.5},
		west = {x = -3, y = 3, rot = 2 * math.pi - math.pi / 2.5},
	},
	stun = {x = 2, y = 2, rot = 0},
	ox = 15,
	oy = 26,
	lightattack = {'swing1', 'swing2'},
	dtype = 'slash',
	baseDamage = 75,
	aiAttackRange = 40,
	staminaCost = 18,
	backstabBonus = 3,
	scaling = {
		strength = 0.8,
		dexterity = 0.8,
		intelligence = 0,
		soulpower = 0,
	},
	weight = 5,
	stundam = 0.2,
	bdam = 10,
	desc = 'A reliable sword whose design is as old as man.  Shortswords are fast, powerful, and easy to use.',
	knockback = -0.15,
}

return weapons